BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `pricequotation_category` (
	`id`	integer NOT NULL PRIMARY KEY AUTOINCREMENT,
	`name`	varchar ( 200 ) NOT NULL UNIQUE
);
INSERT INTO `pricequotation_category` (id,name) VALUES (1,'All Purpose Cleaners'),
 (2,'Presoaks'),
 (3,'Degreasers'),
 (4,'Solvent Base Dressing'),
 (5,'Water Base Dressing'),
 (6,'Body Shop Safe Dressing'),
 (7,'Soap and Shampoo'),
 (8,'Carpet Cleaner'),
 (9,'Polish and Wax'),
 (10,'Compound'),
 (11,'Solvent Cleaner'),
 (12,'Glass Cleaner'),
 (13,'Wheel Cleaner'),
 (14,'Industrial Cleaner'),
 (15,'Air Freshener'),
 (16,'Wonder Wafer'),
 (17,'Paint Sealant'),
 (18,'Aerosol'),
 (19,'Smoke and Odor Aerosol'),
 (20,'Carpet and Vinyl Dye'),
 (21,'Tire, Wheel & Engine'),
 (22,'Foamer & Brush/Cloth Shampoo'),
 (23,'Conditioner'),
 (24,'Polish'),
 (25,'Sealant & Rinse Aid'),
 (26,'Smart Base Soap'),
 (27,'Extra Profit'),
 (28,'Buffing Pads & Bonnets'),
 (29,'Dimple and Microfiber Pads'),
 (30,'Cyclo Pads'),
 (31,'Detailing Accessories'),
 (32,'Brushes'),
 (33,'Drum Pumps'),
 (34,'Polishers & Accessories'),
 (35,'Pressure Washer'),
 (36,'Extractor'),
 (37,'Bottles & Sprayers'),
 (38,'Sure Shot Sprayers'),
 (39,'Tornador'),
 (40,'Dema Dispenser'),
 (41,'Vacuum Hoses & Accessories'),
 (42,'Dispensing Equipment'),
 (43,'Versa-Tags, w/Rings'),
 (44,'Window Stickers'),
 (45,'Service Dispatch Numbers'),
 (46,'Plastic Seat Covers & Floor Mats'),
 (47,'Paper Towels & Toilet Tissue'),
 (48,'Can Liners'),
 (49,'Miscellaneous Janitorial'),
 (50,'Hand Soap & Accessories');
COMMIT;
